apiVersion: apps/v1
kind: Deployment
metadata:
  name: preferences-query-deployment
  labels:
    app: preferences-query
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preferences-query
  template:
    metadata:
      labels:
        app: preferences-query
    spec:
      containers:
        - name: preferences-query
          image: mjoaquim12/preferences-query-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: AXONSERVER_HOSTNAME
              value: axonserver
---
apiVersion: v1
kind: Service
metadata:
  name: preferences-query-service
spec:
  selector:
    app: preferences-query
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081